drop schema `mydb`; 


-- MySQL Script generated by MySQL Workbench
-- 03/29/16 12:19:05
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`School`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`School` (
  `SchoolID` INT NOT NULL,
  `SchoolName` VARCHAR(45) NULL,
  PRIMARY KEY (`SchoolID`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Login` (
  `LoginID` INT NOT NULL,
  `Username` VARCHAR(15) NULL,
  `Pasword` VARCHAR(15) NULL,
  PRIMARY KEY (`LoginID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Room` (
  `RoomID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Location` VARCHAR(45) NULL,
  PRIMARY KEY (`RoomID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TimeTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TimeTable` (
  `TimeTableID` INT NOT NULL,
  `Week` VARCHAR(45) NULL,
  `Day` VARCHAR(45) NULL,
  `Course` VARCHAR(45) NULL,
  `Room` VARCHAR(45) NULL,
  PRIMARY KEY (`TimeTableID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RoomTime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RoomTime` (
  `RoomTimeID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Location` VARCHAR(45) NULL,
  `RoomID` INT NULL,
  `TimeTableID` INT NULL,
  PRIMARY KEY (`RoomTimeID`),
  CONSTRAINT `RoomID`
    FOREIGN KEY (`RoomTimeID`)
    REFERENCES `mydb`.`Room` (`RoomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TimeTableID`
    FOREIGN KEY (`TimeTableID`)
    REFERENCES `mydb`.`TimeTable` (`TimeTableID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ClassSubject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ClassSubject` (
  `ClassSubjectID` INT NOT NULL,
  `Class` VARCHAR(45) NULL,
  `Subject` VARCHAR(45) NULL,
  `SchoolID` INT NULL,
  `RoomTimeID` INT NULL,
  PRIMARY KEY (`ClassSubjectID`),
  CONSTRAINT `SchoolID`
    FOREIGN KEY (`SchoolID`)
    REFERENCES `mydb`.`School` (`SchoolID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RoomTimeID`
    FOREIGN KEY (`RoomTimeID`)
    REFERENCES `mydb`.`RoomTime` (`RoomTimeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Guardian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Guardian` (
  `GuardianID` INT NOT NULL,
  `Firstname` VARCHAR(45) NULL,
  `Lastname` VARCHAR(45) NULL,
  `StudentID` INT NULL,
  PRIMARY KEY (`GuardianID`),
  CONSTRAINT `StudentID`
    FOREIGN KEY (`StudentID`)
    REFERENCES `mydb`.`Student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `StudentID` INT NOT NULL,
  `Firstname` VARCHAR(45) NULL,
  `Lastname` VARCHAR(45) NULL,
  PRIMARY KEY (`StudentID`))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`StudentSubject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StudentSubject` (
  `StudentSubjectID` INT NOT NULL,
  `Subject` VARCHAR(45) NULL,
  `StudentID` INT NULL,
  `ClassSubjectID` INT NULL,
  PRIMARY KEY (`StudentSubjectID`),
  CONSTRAINT `StudentID2`
    FOREIGN KEY (`StudentID`)
    REFERENCES `mydb`.`Student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ClassSubjectID`
    FOREIGN KEY (`ClassSubjectID`)
    REFERENCES `mydb`.`ClassSubject` (`ClassSubjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;





-- -----------------------------------------------------
-- Table `mydb`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teacher` (
  `TeacherID` INT NOT NULL,
  `Firstname` VARCHAR(45) NULL,
  `Lastname` VARCHAR(45) NULL,
  PRIMARY KEY (`TeacherID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TeacherSubject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TeacherSubject` (
  `TeacherSubjectID` INT NOT NULL,
  `Subject` VARCHAR(45) NULL,
  `TeacherID` INT NULL,
  `ClassSubjectID` INT NULL,
PRIMARY KEY (`TeacherSubjectID`), 
CONSTRAINT `TeacherID2` FOREIGN KEY (`TeacherID`) REFERENCES `mydb`.`Teacher` (`TeacherID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT `ClassSubjectID2` FOREIGN KEY (`ClassSubjectID`) REFERENCES `mydb`.`ClassSubject` (`ClassSubjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Message` (
  `MessageID` INT NOT NULL,
  `SentDatetime` DATETIME NULL,
  `Title` VARCHAR(45) NULL,
  `MessagesText` VARCHAR(45) NULL,
  `RoomTimeID` INT NULL,
  PRIMARY KEY (`MessageID`),
  CONSTRAINT `RoomTimeID2`
    FOREIGN KEY (`RoomTimeID`)
    REFERENCES `mydb`.`RoomTime` (`RoomTimeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recipient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recipient` (
 `RecipientID` INT NULL
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

