-- MySQL Script generated by MySQL Workbench
-- 01/19/16 13:05:23
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teachers` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`students` (
  `student_id` INT NOT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teachers` (
  `teacher_id` INT NOT NULL,
  PRIMARY KEY (`teacher_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subjects` (
  `subject_id` INT NOT NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`classes` (
  `class_id` INT NOT NULL,
  `teachers_teacher_id` INT NOT NULL,
  `subjects_subject_id` INT NOT NULL,
  PRIMARY KEY (`class_id`),
  INDEX `fk_classes_teachers1_idx` (`teachers_teacher_id` ASC),
  INDEX `fk_classes_subjects1_idx` (`subjects_subject_id` ASC),
  CONSTRAINT `fk_classes_teachers1`
    FOREIGN KEY (`teachers_teacher_id`)
    REFERENCES `mydb`.`teachers` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classes_subjects1`
    FOREIGN KEY (`subjects_subject_id`)
    REFERENCES `mydb`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`class_hours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`class_hours` (
  `class_hours_id` INT NOT NULL,
  PRIMARY KEY (`class_hours_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teachers_subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teachers_subjects` (
  `teachers_teacher_id` INT NOT NULL,
  `subjects_subject_id` INT NOT NULL,
  PRIMARY KEY (`teachers_teacher_id`, `subjects_subject_id`),
  INDEX `fk_teachers_has_subjects_subjects1_idx` (`subjects_subject_id` ASC),
  INDEX `fk_teachers_has_subjects_teachers1_idx` (`teachers_teacher_id` ASC),
  CONSTRAINT `fk_teachers_has_subjects_teachers1`
    FOREIGN KEY (`teachers_teacher_id`)
    REFERENCES `mydb`.`teachers` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teachers_has_subjects_subjects1`
    FOREIGN KEY (`subjects_subject_id`)
    REFERENCES `mydb`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student_classes` (
  `classes_class_id` INT NOT NULL,
  `students_student_id` INT NOT NULL,
  PRIMARY KEY (`classes_class_id`, `students_student_id`),
  INDEX `fk_classes_has_students_students1_idx` (`students_student_id` ASC),
  INDEX `fk_classes_has_students_classes1_idx` (`classes_class_id` ASC),
  CONSTRAINT `fk_classes_has_students_classes1`
    FOREIGN KEY (`classes_class_id`)
    REFERENCES `mydb`.`classes` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classes_has_students_students1`
    FOREIGN KEY (`students_student_id`)
    REFERENCES `mydb`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`class_hours_classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`class_hours_classes` (
  `class_hours_class_hours_id` INT NOT NULL,
  `classes_class_id` INT NOT NULL,
  PRIMARY KEY (`class_hours_class_hours_id`, `classes_class_id`),
  INDEX `fk_class_hours_has_classes_classes1_idx` (`classes_class_id` ASC),
  INDEX `fk_class_hours_has_classes_class_hours1_idx` (`class_hours_class_hours_id` ASC),
  CONSTRAINT `fk_class_hours_has_classes_class_hours1`
    FOREIGN KEY (`class_hours_class_hours_id`)
    REFERENCES `mydb`.`class_hours` (`class_hours_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_hours_has_classes_classes1`
    FOREIGN KEY (`classes_class_id`)
    REFERENCES `mydb`.`classes` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
