
drop schema mydb;


-- MySQL Script generated by MySQL Workbench
-- 01/19/16 13:05:23
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;



-- -----------------------------------------------------
-- Table `mydb`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`students` (
  `student_id` INT NOT NULL,
 `student_name` VARCHAR(45),
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teachers` (
  `teacher_id` INT NOT NULL,
`teacher_name` VARCHAR(45),
  PRIMARY KEY (`teacher_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subjects` (
  `subject_id` INT NOT NULL,
`subject_name` VARCHAR(45),
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`classes` (
  `class_id` INT NOT NULL,
  `teachers_teacher_id` INT NOT NULL,
  `subjects_subject_id` INT NOT NULL,
`class_name` VARCHAR(45),
  PRIMARY KEY (`class_id`),
  INDEX `fk_classes_teachers1_idx` (`teachers_teacher_id` ASC),
  INDEX `fk_classes_subjects1_idx` (`subjects_subject_id` ASC),
  CONSTRAINT `fk_classes_teachers1`
    FOREIGN KEY (`teachers_teacher_id`)
    REFERENCES `mydb`.`teachers` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classes_subjects1`
    FOREIGN KEY (`subjects_subject_id`)
    REFERENCES `mydb`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`class_hours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`class_hours` (
  `class_hours_id` INT NOT NULL,
  PRIMARY KEY (`class_hours_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teachers_subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teachers_subjects` (
  `teachers_teacher_id` INT NOT NULL,
  `subjects_subject_id` INT NOT NULL,
  PRIMARY KEY (`teachers_teacher_id`, `subjects_subject_id`),
  INDEX `fk_teachers_has_subjects_subjects1_idx` (`subjects_subject_id` ASC),
  INDEX `fk_teachers_has_subjects_teachers1_idx` (`teachers_teacher_id` ASC),
  CONSTRAINT `fk_teachers_has_subjects_teachers1`
    FOREIGN KEY (`teachers_teacher_id`)
    REFERENCES `mydb`.`teachers` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teachers_has_subjects_subjects1`
    FOREIGN KEY (`subjects_subject_id`)
    REFERENCES `mydb`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student_classes` (
  `classes_class_id` INT NOT NULL,
  `students_student_id` INT NOT NULL,
  PRIMARY KEY (`classes_class_id`, `students_student_id`),
  INDEX `fk_classes_has_students_students1_idx` (`students_student_id` ASC),
  INDEX `fk_classes_has_students_classes1_idx` (`classes_class_id` ASC),
  CONSTRAINT `fk_classes_has_students_classes1`
    FOREIGN KEY (`classes_class_id`)
    REFERENCES `mydb`.`classes` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classes_has_students_students1`
    FOREIGN KEY (`students_student_id`)
    REFERENCES `mydb`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`class_hours_classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`class_hours_classes` (
  `class_hours_class_hours_id` INT NOT NULL,
  `classes_class_id` INT NOT NULL,
  PRIMARY KEY (`class_hours_class_hours_id`, `classes_class_id`),
  INDEX `fk_class_hours_has_classes_classes1_idx` (`classes_class_id` ASC),
  INDEX `fk_class_hours_has_classes_class_hours1_idx` (`class_hours_class_hours_id` ASC),
  CONSTRAINT `fk_class_hours_has_classes_class_hours1`
    FOREIGN KEY (`class_hours_class_hours_id`)
    REFERENCES `mydb`.`class_hours` (`class_hours_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_hours_has_classes_classes1`
    FOREIGN KEY (`classes_class_id`)
    REFERENCES `mydb`.`classes` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO Students (student_id, student_name)
VALUES ('1','Asim');
INSERT INTO Students (student_id, student_name)
VALUES ('2','Thomas');



INSERT INTO Subjects (subject_id, subject_name)
VALUES ('1','Programmering');
INSERT INTO Subjects (subject_id, subject_name)
VALUES ('2','opensource');

INSERT INTO Teachers (teacher_id, teacher_name)
VALUES ('1','Hallgeir');
INSERT INTO Teachers (teacher_id, teacher_name)
VALUES ('2','Janis');







INSERT INTO student_classes (classes_class_id, students_student_id)
VALUES ('1','1');
INSERT INTO student_classes (classes_class_id, students_student_id)
VALUES ('2','2');

INSERT INTO Classes (class_id, teachers_teacher_id, subjects_subject_id, class_name)
VALUES ('1','1','1','1AB');
INSERT INTO Classes (class_id, teachers_teacher_id, subjects_subject_id, class_name)
VALUES ('2','2','2','2AB');